### ISSUE TITLE
Redstone crash

### ISSUE THREAD

**Issue by Kashdeya** [turbodiesel4598/NuclearCraft#124]
Just updated to 2.3a-1.11.2 and everytime I go to mine redstone my server crashes. 

From the looks of it the issue is the Rhodochrosite dropping. Here is a copy of the crash log. 

`java.lang.NullPointerException: Exception in server tick loop
	at nc.handler.DropHandler.addBlockDrop(DropHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1083_DropHandler_addBlockDrop_HarvestDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:271)
	at net.minecraft.block.Block.func_180653_a(Block.java:559)
	at net.minecraft.block.BlockRedstoneOre.func_180653_a(BlockRedstoneOre.java:94)
	at net.minecraft.block.Block.func_176226_b(Block.java:550)
	at net.minecraft.block.Block.func_180657_a(Block.java:722)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:330)
	at oreexcavation.handlers.MiningAgent.tickMiner(MiningAgent.java:229)
	at oreexcavation.handlers.MiningScheduler.tickAgents(MiningScheduler.java:143)
	at oreexcavation.handlers.EventHandler.onTick(EventHandler.java:178)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_EventHandler_onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by turbodiesel4598** [comment]
Yeh, I made a mistake - could you see if this works? Just a quick fix:
https://www.dropbox.com/s/h93m87lzew1j7m4/NuclearCraft-2.3aFixaroo--1.11.2.jar?dl=0

**Comment by Kashdeya** [comment]
Yes that version works great.

**Comment by turbodiesel4598** [comment]
Awesome - I'll get an official fix out soon :)

**Comment by tekman123** [comment]
is there a possibility you could fix it for 1.10.2 as well? cause it's happening on that version as well

**Comment by turbodiesel4598** [comment]
Yep, there will be a fix out shortly - I just happen to be halfway through a rewrite of the recipe system, so the timing of my error was a little unfortunate :P
