### ISSUE TITLE
[1.12.2]Nuclearcraft 2.9b - Crash on client start

### ISSUE THREAD

**Issue by LokeYourLord** [turbodiesel4598/NuclearCraft#228]
I leave this here for you to investigate :) Not much information I can provide, it happens the instance I want to start the game.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NuclearCraft (nuclearcraft)
Caused by: java.lang.NoSuchMethodError: nc.fluid.FluidBase.setColor(I)Lnet/minecraftforge/fluids/Fluid;
	at nc.fluid.FluidBase.<init>(FluidBase.java:21)
	at nc.fluid.FluidGas.<init>(FluidGas.java:17)
	at nc.init.NCFluids.init(NCFluids.java:137)
	at nc.proxy.CommonProxy.preInit(CommonProxy.java:57)
	at nc.proxy.ClientProxy.preInit(ClientProxy.java:41)
	at nc.NuclearCraft.preInit(NuclearCraft.java:34)
```

**Comment by turbodiesel4598** [comment]
I think you are using an old version of Forge - NC is using a method that must not have been added until more recently.
