### ISSUE TITLE
nc.entity.EntityBullet 

### ISSUE THREAD

**Issue by b0bst3r** [turbodiesel4598/NuclearCraft#23]
I don't like creating gits without an explanation what occured prior to the crash but the player concerned is not around.  So going to leave this here and add explanation later in case you go ahh I know what that is :)

http://pastebin.com/EXBndF4M

**Comment by turbodiesel4598** [comment]
Hmmm, strange. I'll see if I can see what's going on.
For noew, a few little new things, and a fix to the explosion bug: https://www.dropbox.com/s/0dsp0uh53dobfd5/NuclearCraft-1.7hopefullynotsobuggydemo.jar?dl=0

**Comment by b0bst3r** [comment]
Thanks, we're getting these a lot I don't know why or what's causing them http://pastebin.com/c93MCfxB

**Comment by b0bst3r** [comment]
ignore this we removed NC as a test and it just moved to another mod, think our world is broken.

**Comment by cpelchat1** [comment]
Any update on this?

java.lang.ClassCastException: nc.entity.EntityBullet cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2017-04-23_21.19.03-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/950368/crash-2017-04-23_21.19.03-client.txt)
[crash-2017-04-21_19.04.36-client.txt](https://github.com/turbodiesel4598/NuclearCraft/files/950369/crash-2017-04-21_19.04.36-client.txt)

**Comment by cpelchat1** [comment]
Also, I followed up on a different crash report, went to the cord of my friends crash, and it was a Nuclear Monster:

[22/4/2017 00:48:43 AM] java.lang.RuntimeException: Could not spawn mod entity ModID: NuclearCraft EntityID: 29 at ( 129.5,64.875, -49.5) Please contact mod author or server admin.

**Comment by turbodiesel4598** [comment]
I'm still unsure of how this crash is caused - there must be an entity ID mismatch between the server and client, which is something I don't have control over. Is there no crash if NC is removed?

**Comment by b0bst3r** [comment]
This is caused by EnderZoo nothing whatsoever to do with NuclearCraft.  This happens when a server changes the enderzoo config (like disabling dirt slinkies) when the clients have not.   If you (like we did) remove NuclearCraft the crash re-occurs with naming a different mod.  To fix re-enable whatever it is you disabled on the server.

**Comment by cpelchat1** [comment]
Okay, that makes sense. Thank you very much for your help, I'm sure this will fix it.

Thanks!
