### ISSUE TITLE
java.lang.IllegalArgumentException in teslacorelib because NC sent a null fluid stack

### ISSUE THREAD

**Issue by rezonant** [turbodiesel4598/NuclearCraft#255]
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.ndrei.teslacorelib.inventory.FluidStorage.fill, parameter resource
        at net.ndrei.teslacorelib.inventory.FluidStorage.fill(FluidStorage.kt)
        at nc.tile.energyFluid.TileEnergyFluid.pushFluid(TileEnergyFluid.java:302)
        at nc.tile.energyFluid.TileBuffer.func_73660_a(TileBuffer.java:23)
        at net.minecraft.world.World.func_72939_s(World.java:1832)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:745)
```

Happened after I placed an XU transfer pipe connecting to a NuclearCraft buffer within a CompactMachine. I had a NC buffer on the bottom of the outside of the compact machine, an NC buffer next to a tunnel on the inside, power was flowing fine. I then accidentally connected the XU transfer pipe which was supplying water via a Fluid Transfer Node to the inside buffer and the server went belly up right away. Cross posting this on both Tesla and NC as I don't know who's at fault.

Complete crash report: https://pastebin.com/ajxjxjF9

**Comment by rezonant** [comment]
Issue filed at Tesla Core Lib: https://github.com/faceofcat/Tesla-Core-Lib/issues/31

**Comment by turbodiesel4598** [comment]
Well, that really shouldn't have happened, as I do check to make sure that no null fluid stacks are sent, but I've put an extra check in now... hopefully that as well as faceofcat's fix will sort it out :)
