### ISSUE TITLE
Crash on adding to Manufactory input slot

### ISSUE THREAD

**Issue by pupnewfster** [turbodiesel4598/NuclearCraft#278]
On a server when I try to add coal dust to the manufactory, the server crashes with the error below. I do not have IC2 installed (last version it worked fine without it). I understand that you removed prepacking the IC2 API with NuclearCraft but I strongly suggest you either include it OR properly make it an optional dependency as there is no real reason that IC2 should be a hard dependency.

NuclearCraft-2.10c--1.12.2

```
java.lang.NoSuchMethodError: nc.tile.processor.TileItemProcessor.removeTileFromENet()V
	at nc.tile.processor.TileItemProcessor.updateBlockType(TileItemProcessor.java:140)
	at nc.tile.processor.TileItemProcessor.updateProcessor(TileItemProcessor.java:102)
	at nc.tile.processor.TileItemProcessor.func_73660_a(TileItemProcessor.java:88)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by turbodiesel4598** [comment]
No prob - I was reasonably thourough, but there probably is IC2 stuff hidden in places (such as here) which I may miss.

**Comment by turbodiesel4598** [comment]
As far as I can tell, this is fixed now in [version 2.10d](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2549003) :)

**Comment by SikiciBebek** [comment]
I have the same Issue on 1.16.5 but only if shift click it my Minecraft just freezes and nothing happens for the next 30mins until i spam clicking until it crashes
https://gist.github.com/SikiciBebek/c0822c627e8ffacc99e631232b58560f

**Comment by Neil2101** [comment]
That also happens to me too
