### ISSUE TITLE
NuclearCraft-2.10g--1.12.2 crash

### ISSUE THREAD

**Issue by DevTimur** [turbodiesel4598/NuclearCraft#290]
// Would you like a cupcake?

Time: 4/16/18 9:09 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NuclearCraft (nuclearcraft)
Caused by: java.lang.StackOverflowError
	at java.util.AbstractCollection.toArray(Unknown Source)
	at com.google.common.collect.Iterables.toArray(Iterables.java:295)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:406)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:391)
	at net.minecraftforge.fluids.FluidRegistry.getRegisteredFluids(FluidRegistry.java:239)
	at nc.util.OreDictHelper.exists(OreDictHelper.java:15)
	at nc.recipe.RecipeMethods.fluidStack(RecipeMethods.java:415)
	at nc.recipe.RecipeMethods.fluidStackList(RecipeMethods.java:434)
	at nc.recipe.RecipeMethods.mekanismFluidStackList(RecipeMethods.java:443)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:132)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:142)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:132)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:142)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:132)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:142)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:132)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:142)
	at nc.recipe.RecipeMethods.buildRecipeObject(RecipeMethods.java:132)
and so on

**Comment by turbodiesel4598** [comment]
Will get a fix out shortly!

**Comment by turbodiesel4598** [comment]
[Fixed!](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2552426)
