### ISSUE TITLE
Client Crash, problem with `OreDict`

### ISSUE THREAD

**Issue by Tollainmear** [turbodiesel4598/NuclearCraft#313]
[First one mentioned Alloy Furnace(See entirely report on gist)](https://gist.github.com/Tollainmear/64196b1348ed70f8a1c498c0ee4cead1)

> Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:512)
	at nc.recipe.RecipeOreStack.matches(RecipeOreStack.java:96)
	at nc.recipe.RecipeStackArray.matches(RecipeStackArray.java:63)
	at nc.recipe.RecipeMethods.matchingIngredients(RecipeMethods.java:366)
	at nc.recipe.BaseRecipe.matchingInputs(BaseRecipe.java:36)
	at nc.recipe.RecipeMethods.getRecipeFromInputs(RecipeMethods.java:48)
	at nc.tile.processor.TileItemProcessor.getRecipe(TileItemProcessor.java:248)
	at nc.tile.processor.TileItemProcessor.outputs(TileItemProcessor.java:287)
	at nc.tile.processor.TileItemProcessor.canProcessStacks(TileItemProcessor.java:200)
	at nc.tile.processor.TileItemProcessor.updateProcessor(TileItemProcessor.java:89)
	at nc.tile.processor.TileItemProcessor.func_73660_a(TileItemProcessor.java:85)
-- Block entity being ticked --
Details:
	Name: nuclearcraft:alloy_furnace // nc.tile.processor.TileProcessor.AlloyFurnace
	Block type: ID #0 (tile.nuclearcraft.alloy_furnace_idle // nc.block.tile.processor.BlockProcessor)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (735,30,443), Chunk: (at 15,1,11 in 45,27; contains blocks 720,0,432 to 735,255,447), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)

[Second one mentioned Melter(See entirely report on gist)](https://gist.github.com/Tollainmear/1a5c50b13d48a18f30fe2bdc0b3a4e94)

> Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:512)
	at nc.recipe.RecipeOreStack.matches(RecipeOreStack.java:96)
	at nc.recipe.RecipeMethods.matchingIngredients(RecipeMethods.java:366)
	at nc.recipe.BaseRecipe.matchingInputs(BaseRecipe.java:36)
	at nc.recipe.RecipeMethods.getRecipeFromInputs(RecipeMethods.java:48)
	at nc.tile.processor.TileItemFluidProcessor.getRecipe(TileItemFluidProcessor.java:308)
	at nc.tile.processor.TileItemFluidProcessor.outputs(TileItemFluidProcessor.java:368)
	at nc.tile.processor.TileItemFluidProcessor.canProcessStacks(TileItemFluidProcessor.java:228)
	at nc.tile.processor.TileItemFluidProcessor.updateProcessor(TileItemFluidProcessor.java:112)
	at nc.tile.processor.TileItemFluidProcessor.func_73660_a(TileItemFluidProcessor.java:108)
 -- Block entity being ticked --
Details:
	Name: nuclearcraft:melter // nc.tile.processor.TileProcessor.Melter
	Block type: ID #0 (tile.nuclearcraft.melter_idle // nc.block.tile.processor.BlockProcessor)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (722,63,431), Chunk: (at 2,3,15 in 45,26; contains blocks 720,0,416 to 735,255,431), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)

Using NC - 2.10m
Forge 2655

**Comment by turbodiesel4598** [comment]
Did this happen as soon as the machine turned on?

**Comment by Tollainmear** [comment]
I have no idea, this report was reported by other players, and with time passed by, no more information reported to me, so these issue might out of date and not easy to replicate, I'll close it now, if anyone has same problem plz open it then ;)

(BTW, this issue might has relation with bungee plugin which called fast connect, just a guess)

**Comment by turbodiesel4598** [comment]
Ok, will do :)
