### ISSUE TITLE
NullPointerException extracting Mekanism gas

### ISSUE THREAD

**Issue by Zekrom64** [turbodiesel4598/NuclearCraft#385]
We've had a crash on our server related to NuclearCraft with a mekanism pipe attempting to extract gas from it. Although the NPE occurred in Mekanism's `GasRegistry` I checked the source code and it could only occur if either a gas in the registry had a null name (unlikely) or null was being passed to it. I suspect that `GasHelper.getGasFromFluid` is creating the null that caused the crash.

We're using the Enigmatica 2 Expert pack with NuclearCraft 2.12e

Important Part:
`java.lang.NullPointerException: Ticking block entity
    at mekanism.api.gas.GasRegistry.getGas(GasRegistry.java:111)
    at nc.util.GasHelper.getGasFromFluid(GasHelper.java:37)
    at nc.tile.internal.fluid.GasTileWrapper.drawGas(GasTileWrapper.java:38)
    at mekanism.common.tile.transmitter.TileEntityPressurizedTube.func_73660_a(TileEntityPressurizedTube.java:69)
    at net.minecraft.world.World.func_72939_s(World.java:1835)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
`

Full crash report: [https://pastebin.com/Mtt8nWkX](https://pastebin.com/Mtt8nWkX)

**Comment by turbodiesel4598** [comment]
Thanks very much for pointing that out! You're probably right in saying it's getting passed a null name. Which gas were you trying to extract, and from which machine?
