### ISSUE TITLE
Null fluid

### ISSUE THREAD

**Issue by QORTEC** [turbodiesel4598/NuclearCraft#41]
the following error is in my logs... NuclearCraft 1.7h

fml-server-latest.log
````
[07:23:24] [Server thread/TRACE] [NuclearCraft/NuclearCraft]: Sending event FMLPostInitializationEvent to mod NuclearCraft
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: ****************************************
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at nc.TERecipes.addTERecipes(TERecipes.java:51)
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at nc.TERecipes.hook(TERecipes.java:21)
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at nc.NuclearCraft.postInit(NuclearCraft.java:1980)
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)...
[07:23:24] [Server thread/WARN] [FML/NuclearCraft]: ****************************************
[07:23:24] [Server thread/TRACE] [NuclearCraft/NuclearCraft]: Sent event FMLPostInitializationEvent to mod NuclearCraft
````

**Comment by turbodiesel4598** [comment]
I wasn't checking to see if ic2coolant was in the FluidDictionary - will be fixed in the latest version, coming out in the next few days.
