### ISSUE TITLE
Tinker's registration conflict with ModernMetals and ConArmory

### ISSUE THREAD

**Issue by LemADEC** [turbodiesel4598/NuclearCraft#452]
As of NuclearCraft 2.13e--1.12.2, Tinker's Construct API will crash at boot due to conflicting registration of the Boron ore.
https://gist.github.com/LemADEC/ef1830f2a359547ef92d57920714eac0
```
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stats to "boron": Stats of type "core" were already registered by Base Metals. Use the events to modify stats.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:232)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:208)
```

This is reproduced with the following mods:
BaseMetals-1.12-2.5.0-beta7.311 (required by ModernMetals)
conarm-1.12.2-1.2.3 (required to trigger the issue)
Mantle-1.12-1.3.3.42 (required by Tinker's Construct)
TConstruct-1.12.2-2.12.0.115 (required to trigger the issue)
OreSpawn-1.12-3.3.1.161 (required by BaseMetals)
ModernMetals-1.12-2.5.0-beta7.144 (required to trigger the issue)

**Comment by turbodiesel4598** [comment]
This is due to, in my view, a slight flaw in the material registration system, but is reasonably simple to protect against :)
