### ISSUE TITLE
NuclearCraft Radiation Rendering Crash

### ISSUE THREAD

**Issue by theron61** [turbodiesel4598/NuclearCraft#481]
Client-side crash using the latest release (2.14):

[11:58:16] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderWorldLastEvent@2bdadc7a:
java.lang.NullPointerException: null
	at net.minecraft.world.World.func_189509_E(World.java:225) ~[amu.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2384) ~[amu.class:?]
	at nc.radiation.RadiationRenders.onRenderWorldLastEvent(RadiationRenders.java:154) ~[RadiationRenders.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3444_RadiationRenders_onRenderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196) [ForgeHooksClient.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1951) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[11:58:16] [Client thread/ERROR] [FML]: Index: 57 Listeners:
[11:58:16] [Client thread/ERROR] [FML]: 0: NORMAL
[11:58:16] [Client thread/ERROR] [FML]: 1: ASM: class thaumcraft.client.fx.ParticleEngine onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 2: ASM: class thaumcraft.client.lib.events.RenderEventHandler renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 3: ASM: class codechicken.lib.internal.HighlightHandler renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 4: ASM: class twilightforest.client.TFClientEvents renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 5: ASM: class WayofTime.bloodmagic.util.handler.event.ClientHandler render(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 6: ASM: class com.teammetallurgy.atum.utils.event.ClientEvents renderlast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 7: ASM: class com.teammetallurgy.atum.utils.event.ClientEvents onRenderLastWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 8: ASM: class vazkii.botania.client.core.handler.LightningHandler onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 9: ASM: class vazkii.botania.client.render.world.SkyblockRenderEvents onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 10: ASM: class vazkii.botania.client.core.handler.AstrolabePreviewHandler onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 11: ASM: class vazkii.botania.client.core.handler.BlockHighlightRenderHandler onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 12: ASM: class vazkii.botania.client.core.handler.MultiblockRenderHandler onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 13: ASM: com.zeitheron.hammercore.client.HammerCoreClient@2dda0d37 clientTick(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 14: ASM: class flaxbeard.immersivepetroleum.common.EventHandler renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 15: ASM: class vazkii.psi.common.core.handler.PlayerDataHandler$EventHandler onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 16: ASM: class vazkii.psi.client.fx.ParticleRenderDispatcher onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 17: ASM: class org.orecruncher.dsurround.client.renderer.SpeechDataRenderer onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 18: ASM: com.brandon3055.brandonscore.client.particle.BCEffectHandler@66ba7401 renderWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 19: ASM: com.brandon3055.brandonscore.utils.BCProfiler@ed89087 renderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 20: ASM: crazypants.enderio.base.teleport.TravelController@5c808d89 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 21: ASM: forestry.core.multiblock.MultiblockEventHandlerClient@2773368b onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 22: ASM: mods.railcraft.client.render.world.GoggleAuraWorldRenderer@10ab4687 onWorldRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 23: ASM: vazkii.botania.common.item.ItemCraftingHalo@7ab636d9 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 24: ASM: dmfmm.catwalks.client.RedOverlayEvent@37572a53 renderCatwalkEmptyFaces(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 25: ASM: class org.dave.compactmachines3.misc.PlayerEventHandler renderRotationIndicator(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 26: ASM: mcjty.rftools.proxy.ClientProxy@58ceb010 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 27: ASM: teamroots.embers.EventManager@1d83fde8 onRenderAfterWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 28: ASM: flaxbeard.immersivepetroleum.common.items.ItemProjector@7686c668 renderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 29: ASM: org.cyclops.integrateddynamics.core.network.diagnostics.NetworkDiagnosticsPartOverlayRenderer@15fda929 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 30: ASM: nc.render.BlockHighlightHandler@6899e330 highlightBlock(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 31: ASM: omtteam.omlib.handler.OMLibEventHandler@29bbe058 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 32: ASM: openblocks.client.renderer.TextureUploader@2be0f2f5 onRenderEnd(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 33: ASM: pcl.opensecurity.client.ClientProxy@7ec3efb6 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 34: ASM: class vazkii.patchouli.client.handler.MultiblockVisualizationHandler onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 35: ASM: me.desht.pneumaticcraft.client.ClientEventHandler@2cfeaa32 onWorldRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 36: ASM: me.desht.pneumaticcraft.client.render.pneumaticArmor.HUDHandler@5beb3cee renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 37: ASM: me.desht.pneumaticcraft.client.semiblock.ClientSemiBlockManager@4800a745 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 38: ASM: me.desht.pneumaticcraft.client.AreaShowManager@59029479 renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 39: ASM: teamroots.roots.EventManager@25a5394a onRenderAfterWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 40: ASM: de.teamlapen.vampirism.client.render.RenderHandler@2e9109e onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 41: ASM: class landmaster.plustic.tools.ToolLaserGun$ProxyClient renderBeam(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 42: ASM: com.brandon3055.draconicevolution.client.handler.ClientEventHandler@31b5de9e renderWorldEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 43: ASM: net.bdew.ae2stuff.misc.OverlayRenderHandler$@5c27f25c onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 44: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@63dba2bc onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 45: ASM: class vazkii.botania.client.core.handler.BoundTileRenderer onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 46: ASM: li.cil.oc.client.renderer.MFUTargetRenderer$@721e22c9 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 47: ASM: li.cil.oc.client.renderer.WirelessNetworkDebugRenderer$@22d92aa6 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 48: ASM: class com.raz.howlingmoon.client.ParticleHandler onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 49: ASM: openblocks.client.SoundEventsManager@73414a2d renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 50: ASM: openblocks.client.model.ModelCraneBackpack@264e6f61 renderFppArm(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 51: ASM: openblocks.client.renderer.entity.EntitySelectionHandler@256e05cb renderEvents(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 52: ASM: reborncore.client.multiblock.MultiblockRenderEvent@4ab042a6 onWorldRenderLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 53: ASM: slimeknights.tconstruct.tools.common.client.RenderEvents@79be653f renderExtraBlockBreak(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 54: ASM: com.rwtema.extrautils2.interblock.FlatTransferNodeHandler@70417373 render(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 55: ASM: journeymap.client.forge.event.WaypointBeaconHandler@220676bd onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 56: ASM: mrtjp.core.world.Messenger$@43cee619 renderMessages(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 57: ASM: nc.radiation.RadiationRenders@3c70e3a8 onRenderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 58: ASM: mrtjp.projectred.core.RenderHalo$@209eb8f3 onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 59: LOW
[11:58:16] [Client thread/ERROR] [FML]: 60: ASM: cofh.core.proxy.EventHandlerRender@772421ea renderExtraBlockBreak(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 61: ASM: de.teamlapen.vampirism.client.gui.VampirismHUDOverlay@2f917b1a onRenderWorldLast(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 62: ASM: hellfirepvp.astralsorcery.client.effect.EffectHandler@45afbd9b onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 63: LOWEST
[11:58:16] [Client thread/ERROR] [FML]: 64: ASM: com.zeitheron.hammercore.client.render.Render3D@53b36b4f renderWorld(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 65: ASM: class malte0811.industrialwires.client.ClientEventHandler renderWorldLastLow(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 66: ASM: hellfirepvp.astralsorcery.client.event.ClientRenderEventHandler@3582d695 onRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
[11:58:16] [Client thread/ERROR] [FML]: 67: ASM: AuroraEffectHandler{name=Aurora Effect} doRender(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V

**Comment by turbodiesel4598** [comment]
Was just fixed in the recent 2.14a ;)
