### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by username90001** [turbodiesel4598/NuclearCraft#793]
idk something this is caused somehow by ocean 

crash report 

Description: Initializing game

java.lang.NoClassDefFoundError: trinity/world/BiomeContaminatedOcean
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.privateGetPublicFields(Class.java:2614)
	at java.lang.Class.getFields(Class.java:1557)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:145)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:115)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:68)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: trinity.world.BiomeContaminatedOcean
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: nc/worldgen/biome/NCBiome
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 20 more
Caused by: java.lang.ClassNotFoundException: nc.worldgen.biome.NCBiome
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.privateGetPublicFields(Class.java:2614)
	at java.lang.Class.getFields(Class.java:1557)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:145)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:115)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:68)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by tomdodd4598** [comment]
Which versions of NC and Trinity are you using?

**Comment by username90001** [comment]
i deleted trinity but ihave new crash for some other reason 

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:422)
	at mezz.jei.startup.StackHelper.getUniqueIdentifierForStack(StackHelper.java:403)
	at mezz.jei.startup.UniqueItemStackListBuilder.add(UniqueItemStackListBuilder.java:25)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:397)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:378)
	at mezz.jei.startup.StackHelper.toItemStackList(StackHelper.java:363)
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:346)
	at mezz.jei.startup.StackHelper.expandRecipeItemStackInputs(StackHelper.java:340)
	at mezz.jei.plugins.vanilla.crafting.ShapelessRecipeWrapper.getIngredients(ShapelessRecipeWrapper.java:33)
	at mezz.jei.recipes.RecipeRegistry.getIngredients(RecipeRegistry.java:290)
	at mezz.jei.recipes.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:274)
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:262)
	at mezz.jei.recipes.RecipeRegistry.addRecipe(RecipeRegistry.java:234)
	at mezz.jei.recipes.RecipeRegistry.addRecipes(RecipeRegistry.java:171)
	at mezz.jei.recipes.RecipeRegistry.<init>(RecipeRegistry.java:98)
	at mezz.jei.startup.ModRegistry.createRecipeRegistry(ModRegistry.java:335)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:81)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by username90001** [comment]
i used last version of nc overhaul from curseforge

**Comment by tomdodd4598** [comment]
The second crash seems to just be that your game ran out of memory - you need to launch the game with more RAM.
