### ISSUE TITLE
Opening fluid options on radiation scrubber crashes the game

### ISSUE THREAD

**Issue by macmv** [turbodiesel4598/NuclearCraft#824]
Repro steps:
- Place radiation scrubber.
- Click on side configuration.
- Game crashes.

The crash report had this stack trace:
```
java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=nuclearcraft:radiation_scrubber, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at nc.tile.ITile.getFacingHorizontal(ITile.java:41)
	at nc.gui.processor.GuiFluidSorptions.<init>(GuiFluidSorptions.java:36)
	at nc.gui.processor.GuiFluidSorptions$Output.<init>(GuiFluidSorptions.java:148)
	at nc.gui.processor.GuiProcessor.sorptionButtonActionPerformed(GuiProcessor.java:210)
	at nc.gui.processor.GuiProcessor$SideConfig.buttonActionPerformed(GuiProcessor.java:306)
```

Let me know if you want the full crash report or anything.

**Comment by tomdodd4598** [comment]
Fixed for the next version (the scrubber isn't supposed to have side configs)!
