### ISSUE TITLE
Index outof bounds Exception

### ISSUE THREAD

**Issue by loveyanbei** [turbodiesel4598/NuclearCraft#94]
1.10.2 -latest

net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at nc.handler.ProcessorRecipeHandler.getInputSize(ProcessorRecipeHandler.java:260) ~[ProcessorRecipeHandler.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.process(TileEnergyItemProcessor.java:210) ~[TileEnergyItemProcessor.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.updateProcessor(TileEnergyItemProcessor.java:82) ~[TileEnergyItemProcessor.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.func_73660_a(TileEnergyItemProcessor.java:69) ~[TileEnergyItemProcessor.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]

**Comment by turbodiesel4598** [comment]
I think I fixed this issue a couple of days ago - just to confirm that is was the same crash I was experiencing, could you explain what happened?

**Comment by loveyanbei** [comment]
an error operating alloy furnace

also cause stackoverflowError on spongeforge

**Comment by turbodiesel4598** [comment]
Yep, sounds like the error that I just fixed (hopefully). And the Spongeforge issues should be fixed, too :)

**Comment by turbodiesel4598** [comment]
Should be fixed in the latest version  2.2 :)

**Comment by loveyanbei** [comment]
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at nc.handler.ProcessorRecipeHandler.getInputSize(ProcessorRecipeHandler.java:288) ~[ProcessorRecipeHandler.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.process(TileEnergyItemProcessor.java:236) ~[TileEnergyItemProcessor.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.updateProcessor(TileEnergyItemProcessor.java:91) ~[TileEnergyItemProcessor.class:?]
        at nc.tile.processor.TileEnergyItemProcessor.func_73660_a(TileEnergyItemProcessor.java:77) ~[TileEnergyItemProcessor.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:226) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2300]
        at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2803) ~[ls.class:?]
        at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjp000(WorldServer.java:2790) ~[ls.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6004) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2157) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
        ... 4 more

Occurred again
On placing Graphite powder into Alloy furnace。

**Comment by loveyanbei** [comment]
on latest 2.2

**Comment by turbodiesel4598** [comment]
Could you try breaking and replacing the machine? It shouldn't even be possible to place graphite dust in the alloy furnace anymore.
